[package]
name = "retsurf"
version = "0.1.0"
edition = "2021"
authors = ["troidem <mxmgorin@gmail.com>"]

[features]
default = []
sdl2-bundled = ["sdl2/bundled"]

[dependencies]
rust-embed="8.7.2"
rustls = {version = "0.23.31", features = ["ring"] }
sdl2 = { version = ">= 0.36, < 0.38", default-features = false, features = ["raw-window-handle"] }
raw-window-handle = "0.6.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
log = "0.4.27"
env_logger = "0.11.8"
libservo = { git = "https://github.com/mxmgorin/servo" }
dpi = "0.1.2"
url = "2.5.7"
keyboard-types = "0.8.1"
egui = "~0.32"
image = "0.25.8"
glow = "0.16.0"
egui_glow = "0.32.3"

[target.'cfg(target_os="macos")'.dependencies.sdl2]
features=["bundled", "static-link"]
version= ">= 0.36, < 0.38"
