[package]
name = "retsurf"
version = "0.1.0"
edition = "2021"
authors = ["troidem <mxmgorin@gmail.com>"]

[dependencies]
rust-embed="8.7.2"
rustls = {version = "0.23.31", features = ["ring"] }
tokio = { version = "1.47.1", features = ["rt-multi-thread", "macros"] }
anyhow = "1.0.99"
sdl2 = { version = "0.38", default-features = false, features = ["unsafe_textures", "raw-window-handle"] }
raw-window-handle = "0.6.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
log = "0.4.27"
env_logger = "0.11.8"
libservo = { git = "https://github.com/mxmgorin/servo" }
dpi = "*"
url = "2.5.7"

[target.'cfg(target_os="macos")'.dependencies.sdl2]
features=["bundled", "static-link"]
version="0.38"
